<?php

return [

    'APP_ENV' => env('APP_ENV'),
    'APP_NAME' => env('APP_NAME'),
    'APP_DEBUG' => env('APP_DEBUG'),
    'APP_URL' => env('APP_URL'),

    'GOOGLE_MAP_API_KEY' => env('GOOGLE_MAP_API_KEY'),
    'VITE_GOOGLE_MAP_API_KEY' => env('VITE_GOOGLE_MAP_API_KEY'),

    'CLOUDFLARE_R2_ACCESS_KEY' => env('CLOUDFLARE_R2_ACCESS_KEY'),
    'CLOUDFLARE_R2_SECRET' => env('CLOUDFLARE_R2_SECRET'),
    'CLOUDFLARE_R2_BUCKET' => env('CLOUDFLARE_R2_BUCKET'),
    'CLOUDFLARE_R2_URL' => env('CLOUDFLARE_R2_URL'),
    'CLOUDFLARE_R2_ENDPOINT' => env('CLOUDFLARE_R2_ENDPOINT'),

    'WHATSAPP_API_URL' => env('WHATSAPP_API_URL'),
    'WHATSAPP_API_KEY' => env('WHATSAPP_API_KEY'),

    'TELESCOPE_ENABLED' => env('TELESCOPE_ENABLED', false),

];
